spring:
  datasource:
    url: jdbc:postgresql://192.168.0.150:5433/finanzas_dev?currentSchema=public
    username: root
    password: 69eacb44
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Valida que el Java encaja con el SQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
server:
  port: 8085